const fieldLists = {
  uid: 'uid',
  userName: 'user_name',
  email: 'email',
  password: 'password',
  dob: 'date_of_birth',
  country: 'country',
  liked: '_liked',
  following: '_following',
  playlists: '_playlists',
  joinedDate: 'joined_date',
  likedId: 'liked_id',
  title: 'title',
  posterURL: 'poster_url',
  duration: 'duration',
  likedDate: 'liked_date',
  playlistId: 'playlist_id',
  playlistName: 'playlist_name',
  description: 'description',
  totalItems: 'total_items',
  createdDate: 'create_date',
  playlistItemsId: 'playlist_items_id',
  playlistItemName: 'items_name',
  addedDate: 'added_date',
  artistId: 'artist_id',
  artistName: 'artist_name',
  profileURL: 'profile_url',
  imageURL: 'image_url',
  mediaType: 'media_type',
  releasedDate: 'released_date',
  isLiked: 'is_liked',
  watchList: '_watch_list',
  itemKey: 'item_key',
  avg_vote: 'average_vote',
};
export default fieldLists;
